---
version: "2026.1.1-beta.1"
image: ghcr.io/sukramj/home-assistant-matter-bridge-addon
slug: hamb-beta
name: Home-Assistant-Matter-Bridge (Beta)
description: Beta Releases of Home Assistant Matter Bridge
url: https://github.com/sukramj/home-assistant-matter-bridge
panel_icon: mdi:hub
panel_title: Matter Bridge (Beta)
homeassistant: 2026.1.1
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
